cc_binary(
    name = "behavior_planner_excercise",
    srcs = [
        "cost.cpp",
        "cost.h",
        "main.cc",
        "road.cc",
        "road.h",
        "vehicle.cc",
        "vehicle.h",
    ],
    deps = [],
)