cc_library(
    name = "MTPNInferenceComponent",
    srcs = ["MTPNInferenceComponent.cc"],
    hdrs = ["MTPNInferenceComponent.h"],
    deps = [
        "@ros2_common_interfaces//:cpp_sensor_msgs",
        "@ros2_diagnostics//:cpp_diagnostic_updater",
        "@ros2_image_common//:image_transport",
        "@ros2_rclcpp//:rclcpp",
        "@ros2_rclcpp//:rclcpp_components",
    ],
)
