# cc_library(
#     name = "NAVLaunch",
#     srcs = ["NAVLaunch.h"],
#     #    hdrs = ["NAVLaunch.h"],
#     deps = [
#         "//component:Component",
#         "//component:ROSComponentFactory",
#         "@ros2_rclcpp//:rclcpp",
#         "@ros2_rclcpp//:rclcpp_components",
#         "@yaml-cpp",
#     ],
# )

# cc_library(
#     name = "ManualCompositionLaunch",
#     srcs = ["ManualCompositionLaunch.cc"],
#     #    hdrs = ["ManualCompositionLaunch.h"],
#     deps = [
#         "//component:Component",
#         #        "//component:ROSComponentFactory",
#         "@ros2_rclcpp//:rclcpp",
#         "@ros2_rclcpp//:rclcpp_components",
#         "@yaml-cpp",
#     ],
# )

# cc_library(
#     name = "DynamicCompositionLaunch",
#     srcs = ["DynamicCompositionLaunch.cc"],
#     #    hdrs = ["DynamicCompositionLaunch.h"],
#     deps = [
#         "//component:Component",
#         "//component:ROSComponentFactory",
#         "@ros2_rclcpp//:rclcpp",
#         "@ros2_rclcpp//:rclcpp_components",
#         "@yaml-cpp",
#     ],
# )
