filegroup(
    name = "json_data",
    srcs = [
        "data/exercise1_check.npy",
        "data/ground_truth.json",
        "data/predictions.json",
    ],
    visibility = ["//visibility:public"],
)
